"""build_features.py – create modelling feature matrix
====================================================

Runs with **one click** (no CLI flags). It will:

1. Load the ward-month burglary panel generated by *ingest_burglary.py*.
2. Add temporal lag features (t-1, t-2, t-12 months).
3. Compute spatial-lag feature (previous-month average among neighbouring
   wards; neighbours defined by shared boundary – Queen contiguity).
4. Join static socio-economic data per ward:
      • Mean IMD 2019 overall score aggregated from full **LSOA-level** CSV.
      • Mid-2022 population from Ward Atlas CSV.
5. Save `features.parquet` for modelling.

Repository layout expected::

    4CBLW00-20-Group-34/
    ├── data_cache/
    │   ├── processed/     ward_month_burglary.parquet (input)
    │   └── lookups/
    │       ├── imd2019_lsoa.csv        (raw full workbook)
    │       ├── ward_atlas_data.csv     (contains 2022 population)
    │       └── LSOA21_WD24_Lookup.csv  (already used by ingest script)
    └── scripts/build_features.py

Make sure all required lookup files are present in the data_cache/lookups directory.

Author : Group-34 · TU/e Data Challenge 2
"""
from __future__ import annotations

import argparse
from pathlib import Path

import geopandas as gpd
import pandas as pd
from tqdm import tqdm

# ----------------------------------------------------------------------------
# Constants & defaults -------------------------------------------------------
# ----------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[1]
PROCESSED_DIR = ROOT / "data_cache/processed"
LOOKUP_DIR = ROOT / "data_cache/lookups"

PANEL_FP = PROCESSED_DIR / "ward_month_burglary.parquet"
GEO_JSON = LOOKUP_DIR / "wards_2024.geojson"
LSOA_WARD_LOOKUP = LOOKUP_DIR / "LSOA21_WD24_Lookup.csv"
IMD_CSV = LOOKUP_DIR / "imd2019_lsoa.csv"
POP_CSV = LOOKUP_DIR / "ward_atlas_data.csv"
FEATURE_FP = PROCESSED_DIR / "features.parquet"

# temporal lags in months
LAGS = [1, 3, 12]

# ----------------------------------------------------------------------------
# Feature engineering helpers ------------------------------------------------
# ----------------------------------------------------------------------------

def add_temporal_lags(df: pd.DataFrame, lags=LAGS) -> pd.DataFrame:
    df = df.sort_values(["WD24CD", "Month"])
    for k in lags:
        df[f"lag_{k}"] = df.groupby("WD24CD")["burglaries"].shift(k).fillna(0)
    return df


def make_neighbors(wards: gpd.GeoDataFrame) -> dict[str, list[str]]:
    """Return adjacency dict keyed by ward code (Queen contiguity)."""
    sindex = wards.sindex
    neighbours: dict[str, list[str]] = {code: [] for code in wards["WD24CD"]}
    for i, row in wards.iterrows():
        geom = row.geometry
        hits = list(sindex.intersection(geom.bounds))
        for j in hits:
            if i == j:
                continue
            if geom.touches(wards.at[j, "geometry"]):
                neighbours[row.WD24CD].append(wards.at[j, "WD24CD"])
    return neighbours


def add_spatial_lag(panel: pd.DataFrame, nbrs: dict[str, list[str]]) -> pd.DataFrame:
    panel = panel.copy()
    panel["lag_spatial_avg"] = 0.0
    months = panel["Month"].drop_duplicates().sort_values().tolist()
    prev_map: dict[str, int] = {}
    for m in tqdm(months, desc="Spatial lags"):
        # build mapping from previous month once per loop
        prev_vals = panel.loc[panel["Month"] == (m - pd.offsets.MonthBegin(1)),
                              ["WD24CD", "burglaries"]]
        prev_map = prev_vals.set_index("WD24CD")["burglaries"].to_dict()
        mask = panel["Month"] == m
        panel.loc[mask, "lag_spatial_avg"] = panel.loc[mask, "WD24CD"].apply(
            lambda code: sum(prev_map.get(n, 0) for n in nbrs.get(code, [])) / max(len(nbrs.get(code, [])), 1)
        )
    return panel


# ----------------------------------------------------------------------------
# Static datasets loaders ----------------------------------------------------
# ----------------------------------------------------------------------------

def load_imd_ward(imd_csv: Path, lookup_csv: Path) -> pd.DataFrame:
    """Aggregate full LSOA-level IMD CSV to ward means."""
    imd = pd.read_csv(imd_csv, usecols=[0, 4],  # LSOA code, IMD score
                      dtype={"LSOA code (2011)": str}).rename(
        columns={"LSOA code (2011)": "LSOA21CD", "Index of Multiple Deprivation (IMD) Score": "imd_score"}
    )
    look = pd.read_csv(lookup_csv, usecols=["LSOA21CD", "WD24CD"], dtype=str)
    merged = imd.merge(look, on="LSOA21CD", how="left").dropna(subset=["WD24CD"])
    ward_imd = merged.groupby("WD24CD", as_index=False)["imd_score"].mean()
    return ward_imd


def load_population(pop_csv: Path) -> pd.DataFrame:
    """Extract resident population from Ward Atlas CSV, prioritizing the latest available year."""
    encodings = ['utf-8', 'cp1252', 'latin1']
    # Adjust candidates based on observed complex headers
    # Prioritize 2013 as it seems the latest available based on debug output structure
    pop_col_candidates = [
        "population and age; all ages; 2013", 
        "population and age; all ages; 2012", 
        "population and age; all ages; 2011",
        "all ages 2022", # Keep original simple names as fallbacks
        "2022", 
        "all ages 2021", 
        "2021", 
        "2011 (census)" 
    ] 
    # Target 'New Code' which is likely the correct header in row 1
    code_col_candidates = ["new code", "ward_code", "codes"] 

    last_error = None # Store the last exception

    for encoding in encodings:
        try:
            # Try reading with header=1 (second row)
            pop = pd.read_csv(pop_csv, encoding=encoding, header=1, low_memory=False) 
            
            # Clean column names (lowercase, strip whitespace) and create a mapping
            cols_map = {c.strip().lower(): c.strip() for c in pop.columns}
            
            code_col_found = None
            for candidate in code_col_candidates:
                if candidate in cols_map:
                    code_col_found = cols_map[candidate]
                    break # Found the code column
            
            pop_col_found = None
            for candidate in pop_col_candidates:
                 if candidate in cols_map:
                    pop_col_found = cols_map[candidate]
                    break # Found the population column

            # If *both* columns were found with this encoding, proceed
            if code_col_found is not None and pop_col_found is not None:
                print(f"Found columns - Code: '{code_col_found}', Population: '{pop_col_found}' using encoding '{encoding}' and header=1")
                out = pop[[code_col_found, pop_col_found]].rename(columns={code_col_found: "WD24CD", pop_col_found: "population"})
                # Ensure population column is numeric, coercing errors to NaN
                out["population"] = pd.to_numeric(out["population"], errors='coerce')
                # Handle potential NaNs introduced by coercion
                if out["population"].isnull().any():
                     print(f"Warning: Coerced non-numeric values to NaN in population column.")
                     # Optional: Decide how to handle NaNs, e.g., fill or drop
                     # out = out.dropna(subset=['population']) 
                     # out['population'] = out['population'].fillna(0) # Example: fill with 0
                return out
            # Else, continue to try the next encoding if columns weren't found

        except UnicodeDecodeError as e:
            # print(f"Encoding {encoding} failed for {pop_csv}. Trying next.") # Optional debug print
            last_error = e
            continue # Try next encoding if this one fails
        except Exception as e: # Catch other potential errors during processing
            print(f"Error processing {pop_csv} with encoding {encoding} (header=1): {e}")
            last_error = e
            continue

    # If loop completes without returning, raise a detailed error
    error_message = (
        f"Could not process {pop_csv}. Failed to find required columns "
        f"(Code candidates: {code_col_candidates}, Pop candidates: {pop_col_candidates}) "
        f"with any attempted encodings: {encodings} (tried header=1)."
    )
    if last_error:
        error_message += f"\nLast error encountered: {last_error}"
        
    raise ValueError(error_message)

# ----------------------------------------------------------------------------
# Main -----------------------------------------------------------------------
# ----------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("-h", "--help", action="help")
    args = parser.parse_args([])  # no external args

    # Check if required files exist
    required_files = [PANEL_FP, GEO_JSON, LSOA_WARD_LOOKUP, IMD_CSV, POP_CSV]
    missing = [f for f in required_files if not f.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing required files:\n" + 
            "\n".join(f"  • {f.relative_to(ROOT)}" for f in missing)
        )

    # core panel
    panel = pd.read_parquet(PANEL_FP)

    # temporal lags
    panel = add_temporal_lags(panel)

    # spatial lag
    wards = gpd.read_file(GEO_JSON)
    wards = wards[["WD24CD", "geometry"]]  # Keep only needed columns
    neighbours = make_neighbors(wards)
    panel = add_spatial_lag(panel, neighbours)

    # static joins
    imd = load_imd_ward(IMD_CSV, LSOA_WARD_LOOKUP)
    pop = load_population(POP_CSV)
    panel = (panel.merge(imd, on="WD24CD", how="left")
                   .merge(pop, on="WD24CD", how="left"))

    # save
    FEATURE_FP.parent.mkdir(parents=True, exist_ok=True)
    panel.to_parquet(FEATURE_FP, index=False)
    print(f"✅ features saved → {FEATURE_FP.relative_to(ROOT)}  shape={panel.shape}")


if __name__ == "__main__":
    main()
